# generated by datamodel-codegen:
#   filename:  i14y_rest_api.json
#   timestamp: 2026-07-10T11:20:06+00:00

from __future__ import annotations

from enum import StrEnum
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class CatalogExportFormat(StrEnum):
    rdf = 'RDF'
    ttl = 'TTL'


class CodeInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str


class CodeListEntriesDataFormat(StrEnum):
    json = 'Json'
    csv = 'Csv'


class CodeListEntrySortProperty(StrEnum):
    code = 'Code'
    position = 'Position'


class CodeListEntryValueType(StrEnum):
    string = 'String'
    numeric = 'Numeric'


class ConceptType(StrEnum):
    code_list = 'CodeList'
    date = 'Date'
    numeric = 'Numeric'
    string = 'String'


class CreationType(StrEnum):
    manual = 'Manual'
    automated = 'Automated'


class DcatCatalogThemeInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str
    theme_taxonomy: str = Field(..., alias='themeTaxonomy')


class DcatCatalogType(StrEnum):
    dataset = 'Dataset'
    data_service = 'DataService'


class EmailInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    email: str


class IdModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID


class IdentifierInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    identifier: str


class IopPersonModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    given_name: str = Field(..., alias='givenName')
    family_name: str = Field(..., alias='familyName')
    email: str


class Language(StrEnum):
    de = 'de'
    en = 'en'
    fr = 'fr'
    it = 'it'
    rm = 'rm'


class LinkedDataFormat(StrEnum):
    ttl = 'Ttl'
    rdf = 'Rdf'
    json_ld = 'JsonLd'


class MappingRelationsDataFormat(StrEnum):
    json = 'Json'
    csv = 'Csv'


class MultiLanguageModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    de: str | None = None
    en: str | None = None
    fr: str | None = None
    it: str | None = None
    rm: str | None = None


class PeriodOfTimeModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    start: AwareDatetime | None = None
    end: AwareDatetime | None = None


class PublicationLevel(StrEnum):
    internal = 'Internal'
    public = 'Public'


class RegistrationStatus(StrEnum):
    incomplete = 'Incomplete'
    candidate = 'Candidate'
    recorded = 'Recorded'
    qualified = 'Qualified'
    standard = 'Standard'
    preferred_standard = 'PreferredStandard'
    superseded = 'Superseded'
    retired = 'Retired'


class ResourceModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    label: MultiLanguageModel | None = None
    uri: str


class SearchResourceType(StrEnum):
    dataset = 'Dataset'
    data_service = 'DataService'
    public_service = 'PublicService'
    concept = 'Concept'
    mapping_table = 'MappingTable'


class SearchStructureOption(StrEnum):
    with_structure = 'WithStructure'
    without_structure = 'WithoutStructure'


class SystemInfoModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    created_at: AwareDatetime | None = Field(None, alias='createdAt')
    creation_type: CreationType | None = Field(None, alias='creationType')
    modified_at: AwareDatetime | None = Field(None, alias='modifiedAt')


class UriInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    uri: str


class VCardKind(StrEnum):
    organization = 'Organization'


class VCardModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    fn: MultiLanguageModel | None = None
    has_address: MultiLanguageModel | None = Field(None, alias='hasAddress')
    has_email: str = Field(..., alias='hasEmail')
    has_telephone: str | None = Field(None, alias='hasTelephone')
    kind: VCardKind | None = None
    note: MultiLanguageModel | None = None


class VocabularyEntryModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str
    name: MultiLanguageModel | None = None
    uri: str | None = None


class ProblemDetails(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    type: str | None = None
    title: str | None = None
    status: int | None = None
    detail: str | None = None
    instance: str | None = None


class AnnotationModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID | None = None
    code_list_entry_id: UUID = Field(..., alias='codeListEntryId')
    identifier: str | None = None
    text: MultiLanguageModel | None = None
    title: str | None = None
    type: str
    uri: str | None = None


class ChannelInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    address: MultiLanguageModel | None = None
    description: MultiLanguageModel | None = None
    email: str | None = None
    fax: str | None = None
    id: UUID | None = None
    identifier: str
    mobile: str | None = None
    opening_hours: str | None = Field(None, alias='openingHours')
    owned_by: list[IdentifierInputModel] | None = Field(None, alias='ownedBy')
    phone: str | None = None
    type: CodeInputModel | None = None
    url: str | None = None


class ChecksumInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    algorithm: CodeInputModel
    checksum_value: str = Field(..., alias='checksumValue')


class ChecksumModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    algorithm: VocabularyEntryModel | None = None
    checksum_value: str | None = Field(None, alias='checksumValue')


class CodeListEntryModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    annotations: list[AnnotationModel] | None = None
    code: str
    concept_id: UUID = Field(..., alias='conceptId')
    description: MultiLanguageModel | None = None
    id: UUID | None = None
    name: MultiLanguageModel
    parent_code: str | None = Field(None, alias='parentCode')
    valid_from: AwareDatetime | None = Field(None, alias='validFrom')
    valid_to: AwareDatetime | None = Field(None, alias='validTo')


class DcatCatalogResourceModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    resource_id: UUID | None = Field(None, alias='resourceId')
    resource_type: DcatCatalogType | None = Field(None, alias='resourceType')


class DcatCatalogThemeModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str
    name: MultiLanguageModel | None = None
    theme_taxonomy: str = Field(..., alias='themeTaxonomy')
    uri: str | None = None


class DcatQualifiedAttributionInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    agent: IdentifierInputModel
    had_role: CodeInputModel = Field(..., alias='hadRole')


class DcatQualifiedRelationInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    had_role: CodeInputModel = Field(..., alias='hadRole')
    relation: ResourceModel


class DcatQualifiedRelationModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    had_role: VocabularyEntryModel | None = Field(None, alias='hadRole')
    relation: ResourceModel | None = None


class IdNameModel(IdModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    name: MultiLanguageModel | None = None


class KeywordModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    label: MultiLanguageModel | None = None
    uri: str | None = None


class MappingTableInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    description: MultiLanguageModel
    identifiers: list[str] | None = None
    keywords: list[KeywordModel] | None = None
    name: MultiLanguageModel
    publisher: IdentifierInputModel
    responsible_deputy: EmailInputModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: EmailInputModel = Field(..., alias='responsiblePerson')
    source: UriInputModel
    target: UriInputModel
    themes: list[CodeInputModel] | None = None
    valid_from: AwareDatetime | None = Field(None, alias='validFrom')
    valid_to: AwareDatetime | None = Field(None, alias='validTo')
    version: str


class MappingTableUriModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    uri: str
    name: MultiLanguageModel | None = None


class PublicServiceInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    business_events: list[CodeInputModel] | None = Field(None, alias='businessEvents')
    channels: list[ChannelInputModel] | None = None
    description: MultiLanguageModel
    identifier: str | None = Field(None, deprecated=True)
    identifiers: list[str] | None = None
    is_described_at: list[IdModel | IdNameModel] | None = Field(
        None, alias='isDescribedAt'
    )
    keywords: list[KeywordModel] | None = None
    languages: list[CodeInputModel] | None = None
    life_events: list[CodeInputModel] | None = Field(None, alias='lifeEvents')
    name: MultiLanguageModel
    publisher: IdentifierInputModel
    relations: list[IdModel | IdNameModel] | None = None
    requires: list[IdModel | IdNameModel] | None = None
    responsible_deputy: EmailInputModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: EmailInputModel | None = Field(None, alias='responsiblePerson')
    sectors: list[CodeInputModel] | None = None
    spatial: list[str] | None = None
    thematic_areas: list[CodeInputModel] | None = Field(None, alias='thematicAreas')
    spatial_ch: list[CodeInputModel] | None = Field(None, alias='spatialCH')


class MappingTableInputModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: MappingTableInputModel | None = None


class PublicServiceInputModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: PublicServiceInputModel | None = None


class CodeListEntryModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[CodeListEntryModel] | None = None


class ConceptInputBase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    description: MultiLanguageModel
    identifier: str | None = Field(None, deprecated=True)
    identifiers: list[str] | None = None
    keywords: list[KeywordModel] | None = None
    name: MultiLanguageModel
    publisher: IdentifierInputModel
    responsible_deputy: EmailInputModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: EmailInputModel = Field(..., alias='responsiblePerson')
    themes: list[CodeInputModel] | None = None
    valid_from: AwareDatetime | None = Field(None, alias='validFrom')
    valid_to: AwareDatetime | None = Field(None, alias='validTo')
    version: str


class DateConceptInput(ConceptInputBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    pattern: str | None = None


class NumericConceptInput(ConceptInputBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    max_value: float = Field(..., alias='maxValue')
    measurement_unit: str | None = Field(None, alias='measurementUnit')
    min_value: float = Field(..., alias='minValue')
    number_decimals: int = Field(..., alias='numberDecimals')
    pattern: str | None = None


class StringConceptInput(ConceptInputBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    max_length: int = Field(..., alias='maxLength')
    min_length: int = Field(..., alias='minLength')
    pattern: str | None = None


class HttpValidationProblemDetails(ProblemDetails):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    errors: dict[str, list[str]] | None = None


class AgentModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    classification: VocabularyEntryModel | None = None
    contact_point: VCardModel | None = Field(None, alias='contactPoint')
    description: MultiLanguageModel | None = None
    home_page: str | None = Field(None, alias='homePage')
    id: UUID | None = None
    identifier: str
    images: list[ResourceModel] | None = None
    name: MultiLanguageModel
    pref_label: MultiLanguageModel = Field(..., alias='prefLabel')
    system: SystemInfoModel
    spatial: list[str] | None = None
    spatial_ch: list[VocabularyEntryModel] | None = Field(None, alias='spatialCH')
    sub_agents: list[IdNameModel] | None = Field(None, alias='subAgents')
    uid: str | None = None


class ChannelModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    address: MultiLanguageModel | None = None
    description: MultiLanguageModel | None = None
    email: str | None = None
    fax: str | None = None
    id: UUID
    identifier: str
    mobile: str | None = None
    opening_hours: str | None = Field(None, alias='openingHours')
    owned_by: list[AgentModel] | None = Field(None, alias='ownedBy')
    phone: str | None = None
    type: VocabularyEntryModel | None = None
    url: str | None = None


class DataServiceInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    access_rights: CodeInputModel = Field(..., alias='accessRights')
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    contact_points: list[VCardModel] | None = Field(None, alias='contactPoints')
    description: MultiLanguageModel
    documentation: list[ResourceModel] | None = None
    endpoint_descriptions: list[ResourceModel] | None = Field(
        None, alias='endpointDescriptions'
    )
    endpoint_urls: list[ResourceModel] | None = Field(None, alias='endpointUrls')
    identifiers: list[str] | None = None
    issued: AwareDatetime | None = None
    keywords: list[KeywordModel] | None = None
    landing_pages: list[ResourceModel] | None = Field(None, alias='landingPages')
    license: CodeInputModel | None = None
    modified: AwareDatetime | None = None
    previous_version: IdModel | IdNameModel | None = Field(
        None, alias='previousVersion'
    )
    publisher: IdentifierInputModel
    responsible_deputy: EmailInputModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: EmailInputModel | None = Field(None, alias='responsiblePerson')
    serves_datasets: list[IdModel | IdNameModel] | None = Field(
        None, alias='servesDatasets'
    )
    themes: list[CodeInputModel] | None = None
    title: MultiLanguageModel
    version: str | None = None
    version_notes: MultiLanguageModel | None = Field(None, alias='versionNotes')


class DataServiceModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    access_rights: VocabularyEntryModel | None = Field(None, alias='accessRights')
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    contact_points: list[VCardModel] | None = Field(None, alias='contactPoints')
    description: MultiLanguageModel | None = None
    documentation: list[ResourceModel] | None = None
    endpoint_descriptions: list[ResourceModel] | None = Field(
        None, alias='endpointDescriptions'
    )
    endpoint_urls: list[ResourceModel] | None = Field(None, alias='endpointUrls')
    id: UUID | None = None
    identifiers: list[str] | None = None
    issued: AwareDatetime | None = None
    keywords: list[KeywordModel] | None = None
    landing_pages: list[ResourceModel] | None = Field(None, alias='landingPages')
    license: VocabularyEntryModel | None = None
    modified: AwareDatetime | None = None
    previous_version: IdModel | IdNameModel | None = Field(
        None, alias='previousVersion'
    )
    publication_level: PublicationLevel | None = Field(None, alias='publicationLevel')
    publication_level_proposal: PublicationLevel | None = Field(
        None, alias='publicationLevelProposal'
    )
    publisher: AgentModel | None = None
    registration_status: RegistrationStatus | None = Field(
        None, alias='registrationStatus'
    )
    registration_status_proposal: RegistrationStatus | None = Field(
        None, alias='registrationStatusProposal'
    )
    responsible_deputy: IopPersonModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: IopPersonModel | None = Field(None, alias='responsiblePerson')
    serves_datasets: list[IdModel | IdNameModel] | None = Field(
        None, alias='servesDatasets'
    )
    system: SystemInfoModel
    themes: list[VocabularyEntryModel] | None = None
    title: MultiLanguageModel | None = None
    version: str | None = None
    version_notes: MultiLanguageModel | None = Field(None, alias='versionNotes')


class DcatCatalogModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    description: MultiLanguageModel
    id: UUID | None = None
    publisher: AgentModel
    system: SystemInfoModel
    theme_taxonomy: list[str] | None = Field(None, alias='themeTaxonomy')
    title: MultiLanguageModel


class DcatCatalogRecordInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    primary_topic: DcatCatalogResourceModel = Field(..., alias='primaryTopic')
    themes: list[DcatCatalogThemeInputModel] | None = None


class DcatCatalogRecordModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    dcat_catalog_id: UUID | None = Field(None, alias='dcatCatalogId')
    id: UUID | None = None
    primary_topic: DcatCatalogResourceModel = Field(..., alias='primaryTopic')
    themes: list[DcatCatalogThemeModel] | None = None


class DcatDistributionInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    access_services: list[IdModel | IdNameModel] | None = Field(
        None, alias='accessServices'
    )
    access_url: ResourceModel = Field(..., alias='accessUrl')
    availability: CodeInputModel | None = None
    byte_size: float | None = Field(None, alias='byteSize')
    checksum: ChecksumInputModel | None = None
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    coverage: list[PeriodOfTimeModel] | None = None
    description: MultiLanguageModel
    documentation: list[ResourceModel] | None = None
    download_url: ResourceModel | None = Field(None, alias='downloadUrl')
    format: CodeInputModel | None = None
    id: UUID | None = None
    identifier: str | None = None
    images: list[ResourceModel] | None = None
    issued: AwareDatetime | None = None
    languages: list[CodeInputModel] | None = None
    license: CodeInputModel | None = None
    media_type: CodeInputModel | None = Field(None, alias='mediaType')
    modified: AwareDatetime | None = None
    packaging_format: CodeInputModel | None = Field(None, alias='packagingFormat')
    rights: str | None = None
    spatial_resolution: float | None = Field(None, alias='spatialResolution')
    temporal_resolution: str | None = Field(None, alias='temporalResolution')
    title: MultiLanguageModel


class DcatDistributionModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    access_services: list[IdModel | IdNameModel] | None = Field(
        None, alias='accessServices'
    )
    access_url: ResourceModel | None = Field(None, alias='accessUrl')
    availability: VocabularyEntryModel | None = None
    byte_size: float | None = Field(None, alias='byteSize')
    checksum: ChecksumModel | None = None
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    coverage: list[PeriodOfTimeModel] | None = None
    description: MultiLanguageModel | None = None
    documentation: list[ResourceModel] | None = None
    download_url: ResourceModel | None = Field(None, alias='downloadUrl')
    format: VocabularyEntryModel | None = None
    id: UUID | None = None
    identifier: str | None = None
    images: list[ResourceModel] | None = None
    issued: AwareDatetime | None = None
    languages: list[VocabularyEntryModel] | None = None
    license: VocabularyEntryModel | None = None
    media_type: VocabularyEntryModel | None = Field(None, alias='mediaType')
    modified: AwareDatetime | None = None
    packaging_format: VocabularyEntryModel | None = Field(None, alias='packagingFormat')
    rights: str | None = None
    spatial_resolution: float | None = Field(None, alias='spatialResolution')
    temporal_resolution: str | None = Field(None, alias='temporalResolution')
    title: MultiLanguageModel | None = None


class DcatQualifiedAttributionModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    agent: AgentModel | None = None
    had_role: VocabularyEntryModel | None = Field(None, alias='hadRole')


class IopConceptInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code_list_entry_default_sort_property: CodeListEntrySortProperty | None = Field(
        None, alias='codeListEntryDefaultSortProperty'
    )
    code_list_entry_value_type: CodeListEntryValueType | None = Field(
        None, alias='codeListEntryValueType'
    )
    code_list_entry_value_max_length: int | None = Field(
        None, alias='codeListEntryValueMaxLength'
    )
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    concept_type: ConceptType = Field(..., alias='conceptType')
    description: MultiLanguageModel
    identifier: str | None = Field(None, deprecated=True)
    identifiers: list[str] | None = None
    keywords: list[KeywordModel] | None = None
    max_length: int | None = Field(None, alias='maxLength')
    max_value: float | None = Field(None, alias='maxValue')
    measurement_unit: str | None = Field(None, alias='measurementUnit')
    min_length: int | None = Field(None, alias='minLength')
    min_value: float | None = Field(None, alias='minValue')
    name: MultiLanguageModel
    number_decimals: int | None = Field(None, alias='numberDecimals')
    pattern: str | None = None
    publisher: IdentifierInputModel
    responsible_deputy: EmailInputModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: EmailInputModel = Field(..., alias='responsiblePerson')
    themes: list[CodeInputModel] | None = None
    valid_from: AwareDatetime | None = Field(None, alias='validFrom')
    valid_to: AwareDatetime | None = Field(None, alias='validTo')
    version: str


class IopConceptModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code_list_entries: list[CodeListEntryModel] | None = Field(
        None, alias='codeListEntries'
    )
    code_list_entry_default_sort_property: CodeListEntrySortProperty | None = Field(
        None, alias='codeListEntryDefaultSortProperty'
    )
    code_list_entry_value_max_length: int | None = Field(
        None, alias='codeListEntryValueMaxLength'
    )
    code_list_entry_value_type: CodeListEntryValueType | None = Field(
        None, alias='codeListEntryValueType'
    )
    concept_type: ConceptType | None = Field(None, alias='conceptType')
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    description: MultiLanguageModel
    id: UUID | None = None
    identifier: str | None = Field(None, deprecated=True)
    identifiers: list[str] | None = None
    is_locked: bool | None = Field(None, alias='isLocked')
    keywords: list[KeywordModel] | None = None
    max_length: int | None = Field(None, alias='maxLength')
    max_value: float | None = Field(None, alias='maxValue')
    measurement_unit: str | None = Field(None, alias='measurementUnit')
    min_length: int | None = Field(None, alias='minLength')
    min_value: float | None = Field(None, alias='minValue')
    name: MultiLanguageModel
    number_decimals: int | None = Field(None, alias='numberDecimals')
    pattern: str | None = None
    publication_level: PublicationLevel | None = Field(None, alias='publicationLevel')
    publication_level_proposal: PublicationLevel | None = Field(
        None, alias='publicationLevelProposal'
    )
    publisher: AgentModel
    registration_status: RegistrationStatus | None = Field(
        None, alias='registrationStatus'
    )
    registration_status_proposal: RegistrationStatus | None = Field(
        None, alias='registrationStatusProposal'
    )
    responsible_deputy: IopPersonModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: IopPersonModel = Field(..., alias='responsiblePerson')
    system: SystemInfoModel
    themes: list[VocabularyEntryModel] | None = None
    valid_from: AwareDatetime | None = Field(None, alias='validFrom')
    valid_to: AwareDatetime | None = Field(None, alias='validTo')
    version: str


class MappingTableModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    description: MultiLanguageModel
    id: UUID | None = None
    identifiers: list[str] | None = None
    keywords: list[KeywordModel] | None = None
    name: MultiLanguageModel
    publication_level: PublicationLevel | None = Field(None, alias='publicationLevel')
    publication_level_proposal: PublicationLevel | None = Field(
        None, alias='publicationLevelProposal'
    )
    publisher: AgentModel
    registration_status: RegistrationStatus | None = Field(
        None, alias='registrationStatus'
    )
    registration_status_proposal: RegistrationStatus | None = Field(
        None, alias='registrationStatusProposal'
    )
    responsible_deputy: IopPersonModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: IopPersonModel = Field(..., alias='responsiblePerson')
    system: SystemInfoModel
    source: MappingTableUriModel
    target: MappingTableUriModel
    themes: list[VocabularyEntryModel] | None = None
    valid_from: AwareDatetime | None = Field(None, alias='validFrom')
    valid_to: AwareDatetime | None = Field(None, alias='validTo')
    version: str


class PublicServiceModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    business_events: list[VocabularyEntryModel] | None = Field(
        None, alias='businessEvents'
    )
    channels: list[ChannelModel] | None = None
    description: MultiLanguageModel
    id: UUID | None = None
    identifier: str | None = Field(None, deprecated=True)
    identifiers: list[str] | None = None
    is_described_at: list[IdModel | IdNameModel] | None = Field(
        None, alias='isDescribedAt'
    )
    keywords: list[KeywordModel] | None = None
    languages: list[VocabularyEntryModel] | None = None
    life_events: list[VocabularyEntryModel] | None = Field(None, alias='lifeEvents')
    name: MultiLanguageModel
    publication_level: PublicationLevel | None = Field(None, alias='publicationLevel')
    publication_level_proposal: PublicationLevel | None = Field(
        None, alias='publicationLevelProposal'
    )
    publisher: AgentModel
    registration_status: RegistrationStatus | None = Field(
        None, alias='registrationStatus'
    )
    registration_status_proposal: RegistrationStatus | None = Field(
        None, alias='registrationStatusProposal'
    )
    relations: list[IdModel | IdNameModel] | None = None
    requires: list[IdModel | IdNameModel] | None = None
    responsible_deputy: IopPersonModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: IopPersonModel | None = Field(None, alias='responsiblePerson')
    sectors: list[VocabularyEntryModel] | None = None
    system: SystemInfoModel
    spatial: list[str] | None = None
    thematic_areas: list[VocabularyEntryModel] | None = Field(
        None, alias='thematicAreas'
    )
    spatial_ch: list[VocabularyEntryModel] | None = Field(None, alias='spatialCH')


class SearchResultModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    access_rights: VocabularyEntryModel | None = Field(None, alias='accessRights')
    business_events: list[VocabularyEntryModel] | None = Field(
        None, alias='businessEvents'
    )
    concept_type: ConceptType | None = Field(None, alias='conceptType')
    description: MultiLanguageModel
    formats: list[VocabularyEntryModel] | None = None
    id: UUID | None = None
    identifier: str
    life_events: list[VocabularyEntryModel] | None = Field(None, alias='lifeEvents')
    publication_level: PublicationLevel | None = Field(None, alias='publicationLevel')
    publication_level_proposal: PublicationLevel | None = Field(
        None, alias='publicationLevelProposal'
    )
    publisher: AgentModel
    registration_status: RegistrationStatus | None = Field(
        None, alias='registrationStatus'
    )
    registration_status_proposal: RegistrationStatus | None = Field(
        None, alias='registrationStatusProposal'
    )
    structure: SearchStructureOption | None = None
    system: SystemInfoModel | None = None
    themes: list[VocabularyEntryModel] | None = None
    title: MultiLanguageModel
    type: SearchResourceType
    valid_to: AwareDatetime | None = Field(None, alias='validTo')
    valid_from: AwareDatetime | None = Field(None, alias='validFrom')
    version: str | None = None


class AgentModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: AgentModel | None = None


class DataServiceInputModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: DataServiceInputModel | None = None


class DataServiceModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: DataServiceModel | None = None


class DcatCatalogModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: DcatCatalogModel | None = None


class DcatCatalogRecordInputModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: DcatCatalogRecordInputModel | None = None


class DcatCatalogRecordModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: DcatCatalogRecordModel | None = None


class IopConceptInputModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: IopConceptInputModel | None = None


class IopConceptModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: IopConceptModel | None = None


class MappingTableModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: MappingTableModel | None = None


class PublicServiceModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: PublicServiceModel | None = None


class AgentModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[AgentModel] | None = None


class DcatCatalogModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[DcatCatalogModel] | None = None


class DcatCatalogRecordModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[DcatCatalogRecordModel] | None = None


class SearchResultModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[SearchResultModel] | None = None


class DataServiceModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[DataServiceModel] | None = None


class IopConceptModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[IopConceptModel] | None = None


class PublicServiceModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[PublicServiceModel] | None = None


class CodeListConceptInput(ConceptInputBase):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    code_list_entry_default_sort_property: CodeListEntrySortProperty | None = Field(
        None, alias='codeListEntryDefaultSortProperty'
    )
    code_list_entry_value_type: CodeListEntryValueType = Field(
        ..., alias='codeListEntryValueType'
    )
    code_list_entry_value_max_length: int = Field(
        ..., alias='codeListEntryValueMaxLength'
    )


class DcatDatasetInputModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    access_rights: CodeInputModel = Field(..., alias='accessRights')
    confidentiality_person: CodeInputModel | None = Field(
        None, alias='confidentialityPerson'
    )
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    contact_points: list[VCardModel] | None = Field(None, alias='contactPoints')
    data_owner: str | None = Field(None, alias='dataOwner')
    description: MultiLanguageModel
    distributions: list[DcatDistributionInputModel] | None = None
    documentation: list[ResourceModel] | None = None
    frequency: CodeInputModel | None = None
    geo_iv_ids: list[CodeInputModel] | None = Field(None, alias='geoIvIds')
    identifiers: list[str] | None = None
    images: list[ResourceModel] | None = None
    is_referenced_by: list[ResourceModel] | None = Field(None, alias='isReferencedBy')
    issued: AwareDatetime | None = None
    keywords: list[KeywordModel] | None = None
    landing_pages: list[ResourceModel] | None = Field(None, alias='landingPages')
    languages: list[CodeInputModel] | None = None
    modified: AwareDatetime | None = None
    previous_version: IdModel | IdNameModel | None = Field(
        None, alias='previousVersion'
    )
    process_id: str | None = Field(None, alias='processId')
    publisher: IdentifierInputModel
    qualified_attributions: list[DcatQualifiedAttributionInputModel] | None = Field(
        None, alias='qualifiedAttributions'
    )
    qualified_attribution_complement: MultiLanguageModel | None = Field(
        None, alias='qualifiedAttributionComplement'
    )
    qualified_relations: list[DcatQualifiedRelationInputModel] | None = Field(
        None, alias='qualifiedRelations'
    )
    relations: list[ResourceModel] | None = None
    responsible_deputy: EmailInputModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: EmailInputModel | None = Field(None, alias='responsiblePerson')
    retention_period: AwareDatetime | None = Field(None, alias='retentionPeriod')
    retention_period_complement: MultiLanguageModel | None = Field(
        None, alias='retentionPeriodComplement'
    )
    spatial: list[str] | None = None
    temporal_coverage: list[PeriodOfTimeModel] | None = Field(
        None, alias='temporalCoverage'
    )
    themes: list[CodeInputModel] | None = None
    title: MultiLanguageModel
    version: str | None = None
    version_notes: MultiLanguageModel | None = Field(None, alias='versionNotes')


class DcatDatasetModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    access_rights: VocabularyEntryModel | None = Field(None, alias='accessRights')
    confidentiality_person: VocabularyEntryModel | None = Field(
        None, alias='confidentialityPerson'
    )
    conforms_to: list[ResourceModel] | None = Field(None, alias='conformsTo')
    contact_points: list[VCardModel] | None = Field(None, alias='contactPoints')
    data_owner: str | None = Field(None, alias='dataOwner')
    description: MultiLanguageModel | None = None
    distributions: list[DcatDistributionModel] | None = None
    documentation: list[ResourceModel] | None = None
    frequency: VocabularyEntryModel | None = None
    geo_iv_ids: list[VocabularyEntryModel] | None = Field(None, alias='geoIvIds')
    id: UUID | None = None
    identifiers: list[str] | None = None
    images: list[ResourceModel] | None = None
    is_referenced_by: list[ResourceModel] | None = Field(None, alias='isReferencedBy')
    issued: AwareDatetime | None = None
    keywords: list[KeywordModel] | None = None
    landing_pages: list[ResourceModel] | None = Field(None, alias='landingPages')
    languages: list[VocabularyEntryModel] | None = None
    modified: AwareDatetime | None = None
    previous_version: IdModel | IdNameModel | None = Field(
        None, alias='previousVersion'
    )
    process_id: str | None = Field(None, alias='processId')
    publication_level: PublicationLevel | None = Field(None, alias='publicationLevel')
    publication_level_proposal: PublicationLevel | None = Field(
        None, alias='publicationLevelProposal'
    )
    publisher: AgentModel | None = None
    qualified_attributions: list[DcatQualifiedAttributionModel] | None = Field(
        None, alias='qualifiedAttributions'
    )
    qualified_attribution_complement: MultiLanguageModel | None = Field(
        None, alias='qualifiedAttributionComplement'
    )
    qualified_relations: list[DcatQualifiedRelationModel] | None = Field(
        None, alias='qualifiedRelations'
    )
    registration_status: RegistrationStatus | None = Field(
        None, alias='registrationStatus'
    )
    registration_status_proposal: RegistrationStatus | None = Field(
        None, alias='registrationStatusProposal'
    )
    relations: list[ResourceModel] | None = None
    responsible_deputy: IopPersonModel | None = Field(None, alias='responsibleDeputy')
    responsible_person: IopPersonModel | None = Field(None, alias='responsiblePerson')
    retention_period: AwareDatetime | None = Field(None, alias='retentionPeriod')
    retention_period_complement: MultiLanguageModel | None = Field(
        None, alias='retentionPeriodComplement'
    )
    system: SystemInfoModel
    spatial: list[str] | None = None
    temporal_coverage: list[PeriodOfTimeModel] | None = Field(
        None, alias='temporalCoverage'
    )
    themes: list[VocabularyEntryModel] | None = None
    title: MultiLanguageModel | None = None
    version: str | None = None
    version_notes: MultiLanguageModel | None = Field(None, alias='versionNotes')


class DcatDatasetInputModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: DcatDatasetInputModel | None = None


class DcatDatasetModelDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: DcatDatasetModel | None = None


class ConceptInputBaseDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: (
        CodeListConceptInput
        | DateConceptInput
        | NumericConceptInput
        | StringConceptInput
        | None
    ) = None


class DcatDatasetModelCollectionDataWrapper(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    data: list[DcatDatasetModel] | None = None
